#!/usr/bin/bash
echo -e "\e[32;1m--updating system...."
apt update && apt upgrade -y

if hash ! gpg > /dev/null 2>&1 ; then
  echo "gpg not foung!, install gnupg..."
  apt install gnupg -y
fi 

if [[ -d $PREFIX/etc/apt/sources.list.d ]]; then
  mkdir -p $PREFIX/etc/apt/sources.list.d
fi
echo "\e[32;1m--adding gpg-key...."
curl -sSL https://github.com/Anon4You/alienkrishn/raw/main/alienkrishn.key | apt-key add 
mv $PREFIX/etc/apt/trusted.gpg $PREFIX/etc/apt/trusted.gpg.d 
echo "deb [trusted=yes arch=all] https://anon4you.github.io/alienkrishn anon main" > $PREFIX/etc/apt/sources.list.d/alienkrishn.list

curl -LO https://github.com/Anon4You/alienkrishn/raw/main/Images/alienkrishn
mv alienkrishn $PATH
chmod +x $PATH/alienkrishn

echo -e "
Alienkrishn repo installed
now update and upgrade you termux
and type \e[32;1malienkrishn\e[0m to see availabe
packages and usage
"
