#!/data/data/com.termux/files/usr/bin/bash
clear
echo -e "
                _____
             ,-\"     \"-.
            / o       o \\
           /   \\     /   \\
          /     )-\"-(     \\
         /     ( 6 6 )     \\
        /       \\ 6 /       \\
       /         )=(         \\
      /   o   .--\"-\"--.   o   \\
     /    I  /  -   -  \\  I    \\
 .--(    (_}y/\\       /\\y{_)    )--.
(    \".___l\\/__\\_____/__\\/l___,\"    )
 \\                                 /
  \"-._      o O o O o O o      _,-\"
      \`--Y--.___________.--Y--'
         |==.\e[4m\e[36;1mAlienkrishn\e[0m.==|
         \`==.___________.=='

++--==[ \e[33mA Custom Termux Apt Repository\e[0m
++--==[ Usage\e[32m : \e[0mapt install < \e[31;1mpackage\e[0m >
++--==[ \e[34mMaitaind By \e[32mAnon4You\e[0m

[1] Follow Developer
[2] Show All Packages
[0] Exit

"
read -p "Akrishn > " pill
if [[ $pill = 1 ]]; then
  xdg-open https://github.com/Anon4You
elif [[ $pill = 2 ]]; then
  echo -e "\a\a\n\e[32;1mlisting all available packages\e[0m"
  sleep 2
  apt list | grep -a "anon"
elif [[ $pill = 0 ]]; then
  exit
fi

